version: '3.8'

services:
  web:
    container_name: nginx_server
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: always
